FROM alpine:3.7

LABEL maintainer="naabOmatic"

### Environment variables
ENV LANG C.UTF-8

### Install path for pyload
ARG INSTALL_PATH="/app"

### Get value from .env file to create user and group
ARG GRP
ARG USR

### Set working directory
WORKDIR ${INSTALL_PATH}

### Create user and group
RUN addgroup -g 1000 -S ${GRP} \
  && adduser -u 1000 -D -H -S -G ${GRP} -s /sbin/nologin ${USR}

### Install packages
RUN apk --no-cache update \
  #Required
  && apk add --no-cache python2 \
    tesseract-ocr \
    tesseract-ocr-data-eus \
    curl \
  #Building only
  && apk add --no-cache --virtual .build-deps \
    libressl-dev \
    python-dev \
    curl-dev \
    g++ \
    gcc \
    py-pip \
    make \
    perl \
    zlib-dev \
    jpeg-dev \
    libev-dev \
    libffi-dev \
    tesseract-ocr-dev \
    leptonica-dev

### Download and compile js engine for (spidermonkey)
RUN wget http://ftp.mozilla.org/pub/mozilla.org/js/js-1.8.0-rc1.tar.gz \
  && tar xzf js-1.8.0-rc1.tar.gz \
  && cd js/src \
  && make BUILD_OPT=1 -f Makefile.ref \
  && make BUILD_OPT=1 JS_DIST=/usr -f Makefile.ref export \
  && cd ${INSTALL_PATH} \
  && rm -rf js*

### Install python packages
RUN pip --no-cache-dir install --upgrade setuptools \
  #Required
  && pip --no-cache-dir install beaker \
    py-getch \
    multipartposthandler \
    evalidate \
    bottle \
    colorama \
    jinja2 \
    markupsafe \
    pycurl \
    rename \
    thrift \
    wsgiserver \
  #Optional
  && pip --no-cache-dir install beautifulsoup \
    pillow-pil \
    colorlog \
    bjoern \
    feedparser \
    tesseract-ocr \
    pyopenssl \
    pycrypto \
    simplejson

### Download latest stable pyload
# Pre-build packages: https://github.com/pyload/pyload/releases.
# Latest stable version (source code): https://github.com/pyload/pyload/archive/stable.zip.
# Latest development version (source code): https://github.com/pyload/pyload/archive/master.zip.
RUN wget https://github.com/pyload/pyload/archive/stable.zip \
  && unzip -q stable.zip \
  && rm -rf stable.zip \
  && mv pyload-stable pyload \
  && cd pyload \
  #echo command simulates Enter keystroke for python command
  && echo -ne '\n' | python pyLoadCore.py --changedir --configdir=/app/pyload/conf \
  && chown -R ${USR}:${GRP} "${INSTALL_PATH}/pyload"

### Cleaning task
RUN apk del --purge .build-deps

### Make those ports available outside this container
EXPOSE 8000 7227 9666

VOLUME ["/app/pyload/conf","/app/pyload/Downloads"]

WORKDIR "${INSTALL_PATH}/pyload"

USER ${USR}

### Run pyload when the container is launched
#-u option used as workaround when pyLoadCore.py prompt
ENTRYPOINT ["python", "-u", "pyLoadCore.py"]
