version: '2'
services:
  pyload:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-compose
      args:
        - USR=${MYUSER}
        - GRP=${MYGROUP}
    container_name: pyload
    restart: always
    #Change default kill signal to SINGINT (CTRL+C) to stop pyload
    stop_signal: SIGINT
    ports:
      - "${WEBUI}:8000"
      - "${REMOTE}:7227"
      - "${CNL}:9666"
    #Use z option to avoid SELinux issue
    volumes:
      - ${CONFIG}:/app/pyload/conf:z
      - ${DOWNLOADS}:/app/pyload/Downloads:z
